const labels = {
  // Basic Info
  basicInfo: '識別情報',
  dataId: 'データID',
  msNumber: '型式番号',
  msName: '名称',
  msNameOptional: 'オプション',
  msIcon: 'イメージ',
  dataViewer: 'プレビュー',
  dataEdit: 'データ編集',
  database: 'データベース',

  // Spec
  spec: '機体性能',
  sensorRank: 'センサーランク',
  motionThrust: '回避運動推力',
  minStraight: '最小直進距離',
  size: '寸法修正値',
  stallSpeed: '失速速度',
  ppLimit: 'PP限界',
  defModifier: '防御修正値',
  walkSpeed: '歩行速度',

  // Types
  receiveTypes: '受け方法',
  thrusters: '推力',
  grappleTypes: '格闘方法',
  shootingTypes: '射撃方法',
  weaponSpecs: '武装',
  shootingAndWeapons: '射撃と武器',
  typesAndSpecs: 'タイプとスペック',

  // Avoidance and Defence
  avoidance: '回避',
  defence: 'シールド防御',
  avoidanceAndDefence: '回避と防御',
  front: '正面',
  side: '側面',
  back: '背面',
  right: '右側面',
  left: '左側面',
  directionLabels: ['正面', '右側面', '左側面', '背面'],
  sameSame: '同方向 同箇所',
  sameDifferent: '同方向 異箇所',
  differentSame: '異方向 同箇所',
  differentDifferent: '異方向 異箇所',

  // Body
  bodyPart: '部位',
  bodySpecs: '箇所',
  head: '頭部',
  leg: '脚',
  body: '胴体',
  arm: '腕',
  backpack: 'BP',
  base: '車体',
  item: '項目',

  // Common
  add: '追加',
  remove: '削除',
  name: '名称',
  value: '値',
  direction: '方向',
  fuel: '推進剤',
  power: '威力',
  destructivePower: '破壊力',
  times: '回数',
  concentration: '集中射撃',
  totalCount: '総数',
  totalCountTimes: '同時撃ち',
  shootingDirection: '射界',
  hitRates: '命中率',
  ammunition: '実弾',
  armor: '装甲',
  dcp: 'DCP',
  hp: '耐久力',
  partExplosion: '部分爆発',
  bodyFlag: '耐久力共有',
  field: 'フィールド',
  value: '値',
  thruster: '推力種類',
  action: '操作',
  thrusterType: '推力種類',
  thrust: '推力',
  receiveType: '受け方法',
  grappleType: '格闘方法',
  receiveMethod: '受け方法',
  receiveRate: '受け率',
  grappleMethod: '格闘方法',
  hitRate: '命中率',
  weaponSpec: '武装',
  weaponName: '武装',

  // Author Info
  authorInfo: '作成者情報',
  author: '作成者',
  editPassword: '編集パスワード'
};

export default labels;